# Generated by Django 3.2.3 on 2024-12-25 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognititon', '0004_rename_thieflocation_criminallastspotted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criminal',
            old_name='aadhar_no',
            new_name='cnic_no',
        ),
        migrations.RenameField(
            model_name='criminallastspotted',
            old_name='aadhar_no',
            new_name='cnic_no',
        ),
    ]
